[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.build]
cmds = ["cd packages/registry && npm install && npm run build"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "cd packages/registry && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
